project_id = "cjywecuakfrzpoqwndcm"

[functions.ai-code-assist]
verify_jwt = false

[functions.ai-file-generator]
verify_jwt = false

[functions.ai-stream-assist]
verify_jwt = false

[functions.ai-agent-orchestrator]
verify_jwt = false

[functions.pattern-analyzer]
verify_jwt = true

[functions.code-generator]
verify_jwt = false

[functions.ai-multi-provider]
verify_jwt = true
